#!/bin/bash

# Rebuild bins if necessary
bin_files=$(git diff --cached --name-only --diff-filter=ACM "*ast_to_js.*" | tr '\n' ' ')

if [ -n "$bin_files" ] ; then
  npm run build:bin
  git add bin/
fi

# Prettify all JavaScript staged files
js_files=$(git diff --cached --name-only --diff-filter=ACM "*.js*" "*.md" | tr '\n' ' ')

if [ -n "$js_files" ] ; then
  echo "$js_files" | xargs npm run code:format
  echo "$js_files" | xargs git add
fi

# Prettify all Python staged files
py_files=$(git diff --cached --name-only --diff-filter=ACM "*.py" | tr '\n' ' ')

if [ -n "$py_files" ] ; then
  echo "$py_files" | xargs black
  echo "$py_files" | xargs git add
fi

exit 0
