language: python

cache:
  - pip
  - yarn

matrix:
    fast_finish: true
    include:
    - python: 3.6
    - python: 3.7
    - python: 3.8-dev
      sudo: required
      dist: xenial
    allow_failures:
    - python: 3.8-dev

before_install:
    - pip uninstall -y numpy

install:
    - pip install "setuptools>=40.1.0"
    - pip install -e .

before_script:
    - pip install -r requirements_dev.txt
    - yarn

script:
    - pytest -xvv tests
    - black --check .
    - yarn run code:format:check
    - safety check
