language: python

cache:
  - pip
  - yarn

python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - ASTOR="astor>=0.7,<0.8"
  - ASTOR="astor>=0.8,<0.9"

matrix:
  fast_finish: true

before_install:
  - pip uninstall -y numpy

install:
  - pip install "setuptools>=40.1.0"
  - pip install -e .
  - pip install $ASTOR

before_script:
  - pip install -r requirements_dev.txt
  - yarn

script:
  - pytest -xvv tests
  - black --check .
  - yarn run code:format:check
